server:
  port: 8082

spring:
  mvc:
    static-path-pattern: /static/**
    dispatch-options-request: false
  application:
    name: pay-api

  ##freemarker
  freemarker:
    cache: false
    check-template-location: true
    charset: utf-8
    suffix: .ftl

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    ##启用从数据库列名A_COLUMN到驼峰大小写Java属性名aColumn的自动映射。
    map-underscore-to-camel-case: true
    ##允许JDBC支持生成的键
    use-generated-keys: true
    ##开启日志打印
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  hystrix:
    enabled: true

################################################自定义################################################

snowflake:
  #数据中心
  data-center-id: 0
  #最大worker id
  worker-id-max: 31

security:
  rsa:
    key-size: 1024

order:
  trade:
    number-prefix: TO

#交易相关配置
trade:
  #预下单url
  pre-order-url: http://pay-api:8081/trade/preOrder/
  #最大预警次数
  warn-times-max: 10