server:
  port: 8081

spring:
  mvc:
    static-path-pattern: /static/**
    dispatch-options-request: false
  application:
    name: pay-api

  ##freemarker
  freemarker:
    cache: false
    check-template-location: true
    charset: utf-8
    suffix: .ftl

mybatis:
  mapper-locations: /mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

feign:
  hystrix:
    enabled: true